### ISSUE TITLE
Convert town-level results to CSV

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ct#1]
For Connecticut town-level results, our CSV files should have the following headers:

`county`, `town`, `precinct`,`office`, `district`, `party`, `candidate`, `votes`

With one line per candidate result per precinct. Here's [an example from Massachusetts](https://github.com/openelections/openelections-data-ma/blob/master/2016/20161108__ma__general__brookline__precinct.csv).

The CSV files should be named `YYMMDD__ct__{election_type}__{town}__precinct.csv`

**Comment by brianloveswords** [comment]
I made a first pass, let me know what needs to be fixed or normalized before I export it and make a PR.

[2016 Darien Presidential Election.xlsx](https://github.com/openelections/openelections-data-ct/files/1005043/2016.Darien.Presidential.Election.xlsx)

[GDocs link](https://docs.google.com/spreadsheets/d/1TmV7wzgoUd7Vq4RIo1ctpsgJufSxzP0ow1hIP72UFGQ/edit?usp=sharing)

**Comment by dwillis** [comment]
Thanks, @brianloveswords! The one thing I see is that the values currently in `district` should be in the `precinct` column, while offices that have a district (like US House) should have the district number in the `district` column.

**Comment by brianloveswords** [comment]
@dwillis got it, I'll fix those up in a minute and send a PR
